function [ eVarray, intensityarray, errmsg ] = findSpec( dm3_struct, r, c )
%FINDSPEC gives EELS spectrum at specified pixel
%   dm3_struct is the structure generated by DM3Import, 
%   (r,c) is the pixel location, row, column
%   eVarray is the array of energy loss, intensityarray is the
%   corresponding array of intensities, and errmsg is the error message,
%   which is set to 'NULL' if there is no error message.

errmsg = 'NULL';

if not(strcmp(dm3_struct.zaxis.units, 'eV'))
    errmsg = 'NOT A SPECTRUM IMAGE!' ;
    eVarray =[];
    intensityarray = [];
else
    disp = dm3_struct.zaxis.scale;%dispersion in eV/channel
    orig = dm3_struct.zaxis.origin; 
    data_dims = size(dm3_struct.image_data);
    
    numdata = dm3_struct.image_data;
   
    if (r<= data_dims(1) && c <= data_dims(2) )
        n_channels = data_dims(3); % number of channels. 
        eVarray = linspace(0, (n_channels-1)*disp, n_channels);
        eVarray = eVarray - eVarray(orig); % shift zero loss peak pos to 0
        intensityarray = numdata(r,c,:);   %because DM3 interchanges r and c
        intensityarray = reshape(intensityarray, [1,n_channels]);
        
    else
        errmsg = 'PIXEL OUT OF BOUNDS';
        eVarray =[];
        intensityarray =[];
    end
end


end